<a href="https://colab.research.google.com/github/AkshithaRao123/Iris-Flower-Classification/blob/main/IrisClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Importing necessary packages

In [2]:
import pandas as pd
import numpy as np

Importing and exploring the dataset

In [3]:
df = pd.read_csv('/content/drive/MyDrive/IrisClassification/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


Cleaning the dataset

In [5]:
df = df.drop('Id', axis=1)
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
species = set(list(df['Species']))
print(species)

{'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'}


In [7]:
targetid = {'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2}
key_list = list(targetid.keys())
val_list = list(targetid.values())

In [8]:
lst = []

for i in range(len(df['Species'])):
  s = df['Species'][i]
  lst.append(targetid[s])

df['target'] = lst

In [9]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species  \
0              5.1           3.5            1.4           0.2     Iris-setosa   
1              4.9           3.0            1.4           0.2     Iris-setosa   
2              4.7           3.2            1.3           0.2     Iris-setosa   
3              4.6           3.1            1.5           0.2     Iris-setosa   
4              5.0           3.6            1.4           0.2     Iris-setosa   
..             ...           ...            ...           ...             ...   
145            6.7           3.0            5.2           2.3  Iris-virginica   
146            6.3           2.5            5.0           1.9  Iris-virginica   
147            6.5           3.0            5.2           2.0  Iris-virginica   
148            6.2           3.4            5.4           2.3  Iris-virginica   
149            5.9           3.0            5.1           1.8  Iris-virginica   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 6 columns]

Assigning features and labels

In [10]:
x = df.iloc[:, :-2].values
y = df.iloc[:, -1].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Splitting into train and test sets

In [12]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.25, random_state = 40)

In [13]:
dct = {'0':0, '1':0, '2':0}

for i in ytrain:
  if i==0:
    dct['0']+=1
  if i==1:
    dct['1']+=1
  if i==2:
    dct['2']+=1

dct

{'0': 36, '1': 37, '2': 39}

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(xtrain)
scaler.transform(xtest)

array([[-1.83279578, -0.14714607, -1.44424704, -1.34956491],
       [-0.36568588, -0.14714607,  0.38802956,  0.37560323],
       [ 0.61238739,  0.31064169,  0.84609871,  1.43724515],
       [ 2.20175646,  1.68400498,  1.64771972,  1.30453991],
       [-0.48794504, -1.29161547,  0.10173634,  0.11019274],
       [ 0.49012824,  0.76842946,  1.01787464,  1.56995039],
       [ 0.36786908, -1.97829711,  0.38802956,  0.37560323],
       [-0.36568588, -0.83382771,  0.21625363,  0.11019274],
       [-0.6102042 , -0.14714607,  0.38802956,  0.37560323],
       [-0.85472251,  0.76842946, -1.38698839, -1.34956491],
       [-0.48794504, -1.06272159,  0.33077091, -0.0225125 ],
       [-1.34375915,  0.76842946, -1.27247111, -1.34956491],
       [-1.09924083,  0.99732334, -1.44424704, -1.21685966],
       [ 0.36786908, -0.60493383,  0.55980549,  0.77371895],
       [-0.24342672, -1.06272159, -0.18455688, -0.28792298],
       [ 0.97916487,  0.53953558,  1.07513328,  1.70265564],
       [ 0.49012824, -0.

Training the model

#### Using Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
obj = LogisticRegression()

obj.fit(xtrain,ytrain)

LogisticRegression()

In [17]:
ypred = obj.predict(xtest)

In [18]:
print(ypred)

predictions = pd.DataFrame(list(zip(xtest, ypred, ytest)), columns=['X','Predicted','Actual'])

[0 1 2 2 1 2 1 1 1 0 1 0 0 2 1 2 2 2 1 1 2 2 1 0 1 0 0 2 0 1 1 0 0 0 0 2 0
 0]


In [19]:
def match(val):
  pos = val_list.index(val)
  v = key_list[pos]
  return v

In [20]:
predictions

X  Predicted  Actual
0   [4.4, 3.0, 1.3, 0.2]          0       0
1   [5.6, 3.0, 4.5, 1.5]          1       1
2   [6.4, 3.2, 5.3, 2.3]          2       2
3   [7.7, 3.8, 6.7, 2.2]          2       2
4   [5.5, 2.5, 4.0, 1.3]          1       1
5   [6.3, 3.4, 5.6, 2.4]          2       2
6   [6.2, 2.2, 4.5, 1.5]          1       1
7   [5.6, 2.7, 4.2, 1.3]          1       1
8   [5.4, 3.0, 4.5, 1.5]          1       1
9   [5.2, 3.4, 1.4, 0.2]          0       0
10  [5.5, 2.6, 4.4, 1.2]          1       1
11  [4.8, 3.4, 1.6, 0.2]          0       0
12  [5.0, 3.5, 1.3, 0.3]          0       0
13  [6.2, 2.8, 4.8, 1.8]          2       2
14  [5.7, 2.6, 3.5, 1.0]          1       1
15  [6.7, 3.3, 5.7, 2.5]          2       2
16  [6.3, 2.7, 4.9, 1.8]          2       2
17  [6.7, 3.3, 5.7, 2.1]          2       2
18  [6.8, 2.8, 4.8, 1.4]          1       1
19  [5.2, 2.7, 3.9, 1.4]          1       1
20  [6.4, 2.8, 5.6, 2.2]          2       2
21  [7.6, 3.0, 6.6, 2.1]          2       2
22  [5.5, 2.3, 4.0, 1.3]          1       1
23  [5.1, 3.5, 1.4, 0.3]          0       0
24  [5.6, 2.9, 3.6, 1.3]          1       1
25  [5.7, 3.8, 1.7, 0.3]          0       0
26  [4.3, 3.0, 1.1, 0.1]          0       0
27  [6.5, 3.0, 5.5, 1.8]          2       2
28  [4.9, 3.1, 1.5, 0.1]          0       0
29  [5.5, 2.4, 3.7, 1.0]          1       1
30  [6.0, 2.2, 4.0, 1.0]          1       1
31  [5.1, 3.3, 1.7, 0.5]          0       0
32  [5.0, 3.4, 1.6, 0.4]          0       0
33  [5.3, 3.7, 1.5, 0.2]          0       0
34  [4.7, 3.2, 1.3, 0.2]          0       0
35  [6.4, 2.8, 5.6, 2.1]          2       2
36  [4.6, 3.4, 1.4, 0.3]          0       0
37  [4.4, 3.2, 1.3, 0.2]          0       0

Evaluating the model

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
print(confusion_matrix(ytest,ypred))

[[14  0  0]
 [ 0 13  0]
 [ 0  0 11]]


In [23]:
from sklearn.metrics import recall_score,accuracy_score

In [24]:
score = recall_score(ytest,ypred, average='weighted')
print("Recall score: ", score)

Recall score:  1.0


In [25]:
score = accuracy_score(ytest, ypred)
print("Accuracy score: ", score)

Accuracy score:  1.0


#### Using Decision Tree

In [26]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.25, random_state = 40)

In [27]:
ytest

array([0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0])

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
dtree = DecisionTreeClassifier()

In [30]:
dtree.fit(xtrain, ytrain)

DecisionTreeClassifier()

In [31]:
ypred = dtree.predict(xtest)

Evaluating Predictions

In [32]:
predictions = pd.DataFrame(list(zip(xtest, ypred, ytest)), columns = ['X','Predicted','Actual'])
predictions

X  Predicted  Actual
0   [4.4, 3.0, 1.3, 0.2]          0       0
1   [5.6, 3.0, 4.5, 1.5]          1       1
2   [6.4, 3.2, 5.3, 2.3]          2       2
3   [7.7, 3.8, 6.7, 2.2]          2       2
4   [5.5, 2.5, 4.0, 1.3]          1       1
5   [6.3, 3.4, 5.6, 2.4]          2       2
6   [6.2, 2.2, 4.5, 1.5]          1       1
7   [5.6, 2.7, 4.2, 1.3]          1       1
8   [5.4, 3.0, 4.5, 1.5]          1       1
9   [5.2, 3.4, 1.4, 0.2]          0       0
10  [5.5, 2.6, 4.4, 1.2]          1       1
11  [4.8, 3.4, 1.6, 0.2]          0       0
12  [5.0, 3.5, 1.3, 0.3]          0       0
13  [6.2, 2.8, 4.8, 1.8]          2       2
14  [5.7, 2.6, 3.5, 1.0]          1       1
15  [6.7, 3.3, 5.7, 2.5]          2       2
16  [6.3, 2.7, 4.9, 1.8]          2       2
17  [6.7, 3.3, 5.7, 2.1]          2       2
18  [6.8, 2.8, 4.8, 1.4]          1       1
19  [5.2, 2.7, 3.9, 1.4]          1       1
20  [6.4, 2.8, 5.6, 2.2]          2       2
21  [7.6, 3.0, 6.6, 2.1]          2       2
22  [5.5, 2.3, 4.0, 1.3]          1       1
23  [5.1, 3.5, 1.4, 0.3]          0       0
24  [5.6, 2.9, 3.6, 1.3]          1       1
25  [5.7, 3.8, 1.7, 0.3]          0       0
26  [4.3, 3.0, 1.1, 0.1]          0       0
27  [6.5, 3.0, 5.5, 1.8]          2       2
28  [4.9, 3.1, 1.5, 0.1]          0       0
29  [5.5, 2.4, 3.7, 1.0]          1       1
30  [6.0, 2.2, 4.0, 1.0]          1       1
31  [5.1, 3.3, 1.7, 0.5]          0       0
32  [5.0, 3.4, 1.6, 0.4]          0       0
33  [5.3, 3.7, 1.5, 0.2]          0       0
34  [4.7, 3.2, 1.3, 0.2]          0       0
35  [6.4, 2.8, 5.6, 2.1]          2       2
36  [4.6, 3.4, 1.4, 0.3]          0       0
37  [4.4, 3.2, 1.3, 0.2]          0       0

In [33]:
print(confusion_matrix(ytest,ypred))

[[14  0  0]
 [ 0 13  0]
 [ 0  0 11]]


In [34]:
score = recall_score(ytest,ypred, average='weighted')
print("Recall score: ", score)

Recall score:  1.0


In [35]:
score = accuracy_score(ytest, ypred)
print("Accuracy score: ", score)

Accuracy score:  1.0


#### Using Gaussian Naive Bayes

In [36]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.25, random_state = 40)

In [37]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [38]:
gnb.fit(xtrain, ytrain)
ypred = gnb.predict(xtest)

In [39]:
ypred

array([0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0])

Evaluating the model

In [40]:
print(confusion_matrix(ytest,ypred))

[[14  0  0]
 [ 0 13  0]
 [ 0  0 11]]


In [41]:
score = recall_score(ytest,ypred, average='weighted')
print("Recall score: ", score)

Recall score:  1.0


In [42]:
score = accuracy_score(ytest, ypred)
print("Accuracy score: ", score)

Accuracy score:  1.0


##### Let's now change the parameters while splitting and see the result

In [43]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.25, random_state = 298)

In [44]:
dct = {'0':0, '1':0, '2':0}

for i in ytrain:
  if i==0:
    dct['0']+=1
  if i==1:
    dct['1']+=1
  if i==2:
    dct['2']+=1

dct

{'0': 40, '1': 40, '2': 32}

In [45]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [46]:
gnb.fit(xtrain, ytrain)
ypred = gnb.predict(xtest)

In [47]:
gnb.fit(xtrain, ytrain)
ypred = gnb.predict(xtest)

In [48]:
ypred

array([0, 1, 2, 2, 2, 2, 1, 1, 0, 2, 0, 0, 2, 0, 1, 1, 2, 0, 1, 2, 2, 1,
       2, 2, 0, 2, 1, 1, 1, 0, 2, 2, 0, 2, 1, 2, 0, 1])

Evaluating the model

In [49]:
predictions = pd.DataFrame(list(zip(xtest, ypred, ytest)), columns = ['X','Predicted','Actual'])
predictions

X  Predicted  Actual
0   [4.9, 3.1, 1.5, 0.1]          0       0
1   [5.7, 2.6, 3.5, 1.0]          1       1
2   [6.7, 3.0, 5.0, 1.7]          2       1
3   [5.8, 2.7, 5.1, 1.9]          2       2
4   [5.7, 2.5, 5.0, 2.0]          2       2
5   [7.2, 3.2, 6.0, 1.8]          2       2
6   [6.3, 2.8, 5.1, 1.5]          1       2
7   [6.1, 2.9, 4.7, 1.4]          1       1
8   [5.0, 3.4, 1.5, 0.2]          0       0
9   [5.8, 2.7, 5.1, 1.9]          2       2
10  [4.9, 3.0, 1.4, 0.2]          0       0
11  [5.4, 3.9, 1.7, 0.4]          0       0
12  [6.3, 2.5, 5.0, 1.9]          2       2
13  [4.7, 3.2, 1.6, 0.2]          0       0
14  [5.5, 2.3, 4.0, 1.3]          1       1
15  [6.0, 2.2, 5.0, 1.5]          1       2
16  [7.1, 3.0, 5.9, 2.1]          2       2
17  [5.1, 3.8, 1.5, 0.3]          0       0
18  [6.1, 2.6, 5.6, 1.4]          1       2
19  [6.3, 3.4, 5.6, 2.4]          2       2
20  [6.5, 3.0, 5.5, 1.8]          2       2
21  [6.0, 2.2, 4.0, 1.0]          1       1
22  [6.2, 3.4, 5.4, 2.3]          2       2
23  [6.3, 2.7, 4.9, 1.8]          2       2
24  [5.0, 3.6, 1.4, 0.2]          0       0
25  [6.5, 3.0, 5.2, 2.0]          2       2
26  [7.0, 3.2, 4.7, 1.4]          1       1
27  [5.5, 2.5, 4.0, 1.3]          1       1
28  [6.6, 2.9, 4.6, 1.3]          1       1
29  [5.1, 3.5, 1.4, 0.3]          0       0
30  [6.7, 2.5, 5.8, 1.8]          2       2
31  [6.1, 3.0, 4.9, 1.8]          2       2
32  [5.4, 3.9, 1.3, 0.4]          0       0
33  [6.9, 3.1, 5.4, 2.1]          2       2
34  [5.6, 3.0, 4.5, 1.5]          1       1
35  [6.4, 2.8, 5.6, 2.2]          2       2
36  [4.8, 3.0, 1.4, 0.3]          0       0
37  [6.3, 3.3, 4.7, 1.6]          1       1

In [50]:
print(confusion_matrix(ytest,ypred))

[[10  0  0]
 [ 0  9  1]
 [ 0  3 15]]


In [51]:
score = recall_score(ytest,ypred, average='weighted')
print("Recall score: ", score)

Recall score:  0.8947368421052632


In [52]:
score = accuracy_score(ytest, ypred)
print("Accuracy score: ", score)

Accuracy score:  0.8947368421052632


#### Decision Trees

In [54]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.25, random_state = 298)

In [55]:
dtree = DecisionTreeClassifier()

In [56]:
dtree.fit(xtrain, ytrain)

DecisionTreeClassifier()

In [57]:
ypred = dtree.predict(xtest)

In [58]:
predictions = pd.DataFrame(list(zip(xtest, ypred, ytest)), columns = ['X','Predicted','Actual'])
predictions

X  Predicted  Actual
0   [4.9, 3.1, 1.5, 0.1]          0       0
1   [5.7, 2.6, 3.5, 1.0]          1       1
2   [6.7, 3.0, 5.0, 1.7]          2       1
3   [5.8, 2.7, 5.1, 1.9]          2       2
4   [5.7, 2.5, 5.0, 2.0]          2       2
5   [7.2, 3.2, 6.0, 1.8]          2       2
6   [6.3, 2.8, 5.1, 1.5]          1       2
7   [6.1, 2.9, 4.7, 1.4]          1       1
8   [5.0, 3.4, 1.5, 0.2]          0       0
9   [5.8, 2.7, 5.1, 1.9]          2       2
10  [4.9, 3.0, 1.4, 0.2]          0       0
11  [5.4, 3.9, 1.7, 0.4]          0       0
12  [6.3, 2.5, 5.0, 1.9]          2       2
13  [4.7, 3.2, 1.6, 0.2]          0       0
14  [5.5, 2.3, 4.0, 1.3]          1       1
15  [6.0, 2.2, 5.0, 1.5]          1       2
16  [7.1, 3.0, 5.9, 2.1]          2       2
17  [5.1, 3.8, 1.5, 0.3]          0       0
18  [6.1, 2.6, 5.6, 1.4]          2       2
19  [6.3, 3.4, 5.6, 2.4]          2       2
20  [6.5, 3.0, 5.5, 1.8]          2       2
21  [6.0, 2.2, 4.0, 1.0]          1       1
22  [6.2, 3.4, 5.4, 2.3]          2       2
23  [6.3, 2.7, 4.9, 1.8]          2       2
24  [5.0, 3.6, 1.4, 0.2]          0       0
25  [6.5, 3.0, 5.2, 2.0]          2       2
26  [7.0, 3.2, 4.7, 1.4]          1       1
27  [5.5, 2.5, 4.0, 1.3]          1       1
28  [6.6, 2.9, 4.6, 1.3]          1       1
29  [5.1, 3.5, 1.4, 0.3]          0       0
30  [6.7, 2.5, 5.8, 1.8]          2       2
31  [6.1, 3.0, 4.9, 1.8]          2       2
32  [5.4, 3.9, 1.3, 0.4]          0       0
33  [6.9, 3.1, 5.4, 2.1]          2       2
34  [5.6, 3.0, 4.5, 1.5]          1       1
35  [6.4, 2.8, 5.6, 2.2]          2       2
36  [4.8, 3.0, 1.4, 0.3]          0       0
37  [6.3, 3.3, 4.7, 1.6]          1       1

Evaluating the model

In [59]:
print(confusion_matrix(ytest,ypred))

[[10  0  0]
 [ 0  9  1]
 [ 0  2 16]]


In [60]:
score = recall_score(ytest,ypred, average='weighted')
print("Recall score: ", score)

Recall score:  0.9210526315789473


In [61]:
score = accuracy_score(ytest, ypred)
print("Accuracy score: ", score)

Accuracy score:  0.9210526315789473


##### Logistic Regression

In [62]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.25, random_state = 298)

In [63]:
from sklearn.linear_model import LogisticRegression

In [64]:
obj = LogisticRegression()

obj.fit(xtrain,ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [65]:
ypred = obj.predict(xtest)

In [66]:
print(ypred)

predictions = pd.DataFrame(list(zip(xtest, ypred, ytest)), columns=['X','Predicted','Actual'])

[0 1 1 2 2 2 1 1 0 2 0 0 2 0 1 1 2 0 2 2 2 1 2 1 0 2 1 1 1 0 2 2 0 2 1 2 0
 1]


In [67]:
predictions

X  Predicted  Actual
0   [4.9, 3.1, 1.5, 0.1]          0       0
1   [5.7, 2.6, 3.5, 1.0]          1       1
2   [6.7, 3.0, 5.0, 1.7]          1       1
3   [5.8, 2.7, 5.1, 1.9]          2       2
4   [5.7, 2.5, 5.0, 2.0]          2       2
5   [7.2, 3.2, 6.0, 1.8]          2       2
6   [6.3, 2.8, 5.1, 1.5]          1       2
7   [6.1, 2.9, 4.7, 1.4]          1       1
8   [5.0, 3.4, 1.5, 0.2]          0       0
9   [5.8, 2.7, 5.1, 1.9]          2       2
10  [4.9, 3.0, 1.4, 0.2]          0       0
11  [5.4, 3.9, 1.7, 0.4]          0       0
12  [6.3, 2.5, 5.0, 1.9]          2       2
13  [4.7, 3.2, 1.6, 0.2]          0       0
14  [5.5, 2.3, 4.0, 1.3]          1       1
15  [6.0, 2.2, 5.0, 1.5]          1       2
16  [7.1, 3.0, 5.9, 2.1]          2       2
17  [5.1, 3.8, 1.5, 0.3]          0       0
18  [6.1, 2.6, 5.6, 1.4]          2       2
19  [6.3, 3.4, 5.6, 2.4]          2       2
20  [6.5, 3.0, 5.5, 1.8]          2       2
21  [6.0, 2.2, 4.0, 1.0]          1       1
22  [6.2, 3.4, 5.4, 2.3]          2       2
23  [6.3, 2.7, 4.9, 1.8]          1       2
24  [5.0, 3.6, 1.4, 0.2]          0       0
25  [6.5, 3.0, 5.2, 2.0]          2       2
26  [7.0, 3.2, 4.7, 1.4]          1       1
27  [5.5, 2.5, 4.0, 1.3]          1       1
28  [6.6, 2.9, 4.6, 1.3]          1       1
29  [5.1, 3.5, 1.4, 0.3]          0       0
30  [6.7, 2.5, 5.8, 1.8]          2       2
31  [6.1, 3.0, 4.9, 1.8]          2       2
32  [5.4, 3.9, 1.3, 0.4]          0       0
33  [6.9, 3.1, 5.4, 2.1]          2       2
34  [5.6, 3.0, 4.5, 1.5]          1       1
35  [6.4, 2.8, 5.6, 2.2]          2       2
36  [4.8, 3.0, 1.4, 0.3]          0       0
37  [6.3, 3.3, 4.7, 1.6]          1       1

Evaluating the model

In [68]:
print(confusion_matrix(ytest,ypred))

[[10  0  0]
 [ 0 10  0]
 [ 0  3 15]]


In [69]:
score = recall_score(ytest,ypred, average='weighted')
print("Recall score: ", score)

Recall score:  0.9210526315789473


In [70]:
score = accuracy_score(ytest, ypred)
print("Accuracy score: ", score)

Accuracy score:  0.9210526315789473
